name: arvorealta
favicon: null
layout_spectrum: 0.1641331766732037
typography_spectrum: 0.07573882979340851
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8485452821478248
  lightness: 0.4155544869136065
  saturation: 0.44657311867922544
  rhythmicContrast: 0.1747415077406913
purpose: []
